version: '3.8'

services:
  # PHP - Apache - Xdebug
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    depends_on:
      - mysql
  # MySQL
  mysql:
    command: ['--default-authentication-plugin=mysql_native_password']
    platform: linux/x86_64
    restart: always
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=dbname
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PORT=3306
    volumes:
      - ./data:/var/lib/mysql
  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
  # Composer
  composer:
    image: composer:latest
    volumes:
      - ./:/app/
volumes:
  mysql_data: { driver: 'local' }
